---
# * Checks for syntax validity of yaml files
name: YAML Lint

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: "."
        description: "Target path for yamllint"

jobs:
  yaml-lint:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Run yamllint
        run: yamllint "${{ inputs.path }}"