---
# * Checks for syntax validity of yaml files
name: YAML Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: "."
        description: "Target path for yamllint"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
         