---
# * Checks for syntax validity of yaml files
name: YAML Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: "."
        description: "Target path for yamllint"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Find YAML files
        id: find-files
        run: |
          find . -type f -name "*.yaml" -not -path "./.git/*" > files.txt
      
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: files.txt
          config_data: |
            extends: default
            rules: 
              new-line-at-end-of-file:
                level: warning
              document-start:
                level: warning
                   sfdsfdsfdfd